# Generated by Django 4.0.4 on 2022-06-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('item_name', models.CharField(max_length=100)),
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_price', models.CharField(max_length=10)),
            ],
        ),
    ]
